### ISSUE TITLE
The requested URL /components was not found on this server

### ISSUE THREAD

**Issue by vacate0506** [niu-grandpa/RabbitUI#4]
问题: 访问官网组件页面报错(The requested URL /components was not found on this server)

步骤:
打开一个新标签页，输入组件网址(如: http://www.rabbitui.cn/docs/introduce)

![sendpix0](https://user-images.githubusercontent.com/46106134/126054814-c15f3cea-326c-4cbe-a84c-f274570e9e08.jpg)
![sendpix1](https://user-images.githubusercontent.com/46106134/126054816-5e5e5291-9ec7-496c-8fbc-c2dd4fd4e216.jpg)

**Comment by niu-grandpa** [comment]
https://niu-grandpa.github.io/rabbit-ui.github.io/
